[build]
  publish = "dist/public"
  command = "vite build"

[build.environment]
  VITE_API_BASE_URL = "https://digital-surprise.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200